# Generated by Django 2.1.2 on 2018-10-29 07:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SchediumTask',
            fields=[
                ('sched_id', models.CharField(default=uuid.uuid4, max_length=200, primary_key=True, serialize=False)),
                ('task_type', models.CharField(default='default', max_length=2000)),
                ('task_id', models.CharField(max_length=2000)),
                ('first', models.BooleanField(default=True)),
                ('start_time', models.FloatField(null=True)),
                ('next_time', models.FloatField()),
                ('end_time', models.FloatField(null=True)),
                ('interval', models.FloatField(null=True)),
                ('is_finished', models.BooleanField(default=False)),
                ('in_sched', models.BooleanField(default=False)),
            ],
        ),
    ]
