# Generated by Django 2.1.2 on 2018-10-29 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedium', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schediumtask',
            name='first',
        ),
        migrations.AlterField(
            model_name='schediumtask',
            name='end_time',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='schediumtask',
            name='interval',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='schediumtask',
            name='next_time',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='schediumtask',
            name='start_time',
            field=models.IntegerField(null=True),
        ),
    ]
