# Generated by Django 2.1.2 on 2018-10-25 14:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('schedium', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schediumdelaymodeltask',
            name='id',
        ),
        migrations.RemoveField(
            model_name='schediumloopmodeltask',
            name='id',
        ),
        migrations.AddField(
            model_name='schediumdelaymodeltask',
            name='is_finished',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='schediumdelaymodeltask',
            name='schedium_id',
            field=models.CharField(default=uuid.uuid4, max_length=200, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='schediumloopmodeltask',
            name='schedium_id',
            field=models.CharField(default=uuid.uuid4, max_length=200, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='schediumloopmodeltask',
            name='is_finished',
            field=models.BooleanField(default=False),
        ),
    ]
