# Generated by Django 2.1.2 on 2018-10-28 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedium', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schediumdelaymodeltask',
            name='in_sched',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='schediumloopmodeltask',
            name='in_sched',
            field=models.BooleanField(default=False),
        ),
    ]
