# Generated by Django 2.1.2 on 2018-10-28 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedium', '0002_auto_20181028_1213'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schediumdelaymodeltask',
            name='in_sched',
        ),
        migrations.RemoveField(
            model_name='schediumloopmodeltask',
            name='in_sched',
        ),
    ]
