# Generated by Django 2.1.2 on 2018-10-29 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedium', '0002_auto_20181029_1009'),
    ]

    operations = [
        migrations.AddField(
            model_name='schediumtask',
            name='last_executed_time',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='schediumtask',
            name='start_time',
            field=models.IntegerField(),
        ),
    ]
